<?php

return array(
	"ACCOUNT_CREATED_SUCCESSFULLY"              => "Your account has been created successfully. You can now log in.",
	"RESET_DATE_EXPIRED"                        => "Your reset link has expired. Please use the reset link within one hour.",
	"PASSWORD_VERIFICATION_PROCESS_FAILED"      => "Verification process failed!",
	"PASSWORD_CHANGE_SUCCESSFUL"                => "Password successfully changed. You can now log in.",
	"DATABASE_SAVE_ERROR"                       => "Database error! Could not write to database.",
	"USERNAME_FIELD_EMPTY"                      => "Username field was empty.",
	"PASSWORD_FIELD_EMPTY"                      => "Password field was empty.",
	"EMAIL_FIELD_EMPTY"                         => "Email field was empty.",
	"USERNAME_ALREADY_TAKEN"                    => "Sorry, that username is already taken. Please choose another one.",
	"EMAIL_ALREADY_TAKEN"                       => "Sorry, that email is already in use. Please choose another one.",
	"USERNAME_DOES_NOT_FIT_PATTERN"             => "Username does not fit the name pattern: only a-Z and numbers are allowed, 2 to 64 characters.",
	"EMAIL_DOES_NOT_FIT_PATTERN"                => "Sorry, your chosen email does not fit into the email naming pattern.",
	"USERNAME_REPEAT_WRONG"                     => "Repeated username is wrong.",
	"PASSWORD_REPEAT_WRONG"                     => "Repeated password value is wrong.",
	"EMAIL_REPEAT_WRONG"                        => "Repeated email is wrong",
	"USERNAME_SAME_AS_OLD_ONE"                  => "That username is the same as your current one. Please choose another one.",
	"EMAIL_SAME_AS_OLD_ONE"                     => "This email address is the same as your current one. Please choose another one.",
	"PASSWORD_TOO_SHORT"                        => "Password has a minimum length of 6 characters.",
	"USERNAME_TOO_LONG"                         => "Username is too long.",
	"USERNAME_OR_PASSWORD_WRONG"                => "The username or password is incorrect. Please try again.",
	"USER_DOES_NOT_EXIST"                       => "This user does not exist.",
	"PASSWORD_CURRENT_INCORRECT"                => "Current password entered was incorrect.",
	"USERNAME_CHANGE_SUCCESSFUL"                => "Your username has been changed successfully.",
	"EMAIL_CHANGE_SUCCESSFUL"                   => "Your email address has been changed successfully.",
	"PASSWORD_RESET_MAIL_SUCCESSFUL"            => "A password reset mail has been sent successfully.",
	"PASSWORD_RESET_COMBINATION_FAIL"           => "Username / Verification code combination does not exist.",
	"UNKNOWN_ERROR"                             => "Unknown error occurred!",
);
